### ISSUE TITLE
menu_wrap.c:930: undefined reference to `STR2CSTR'

### ISSUE THREAD

**Issue by tallica** [rlane/ncursesw-ruby#1]
Ncursesw still doesn't build in Ruby 1.9. There're missing definitions for STR2CSTR in menu_wrap.c.

**Comment by rlane** [comment]
It builds fine for me on 1.9.2p136, but I made a change that should fix it for you.

**Comment by tallica** [comment]
Now it builds fine. Thank you.
